name: Healthz Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:13 # Use the PostgreSQL Docker image
        env:
          POSTGRES_USER: postgres # Replace with your PostgreSQL username
          POSTGRES_PASSWORD: 1234 # Replace with your PostgreSQL password
          POSTGRES_DB: cloud-db # Replace with your PostgreSQL database name
        ports:
          - 5432:5432 # Map container port 5432 to host port 5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: npm run migrate # Replace with your actual migration command

      - name: Run tests
        run: npm test # Replace with your test command
