name: Packer Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  packer-build:
    name: Packer build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip web application
        run: |
          cd ${{ github.workspace }}
          zip -r webapp.zip .
          ls -l
        working-directory: ${{ github.workspace }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Initialize Packer
        run: packer init aws-debian.pkr.hcl

      - name: Packer build
        run: |
          packer build -var 'source_ami=${{ vars.SOURCE_AMI }}' \
                      -var 'subnet_id=${{ vars.SUBNET_ID }}' \
                      -var 'instance_type=${{ vars.INSTANCE_TYPE }}' \
                      -var 'region=${{ vars.REGION }}' \
                      -var 'zip_file_name=${{ github.workspace }}/webapp.zip' \
                      aws-debian.pkr.hcl
        working-directory: ${{ github.workspace }}
